export const GET_BOARDS = 'GET_BOARDS';
export const ADD_BOARD = 'ADD_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const RENAME_BOARD = 'RENAME_BOARD';
export const SET_ACTIVE_BOARD = 'SET_ACTIVE_BOARD';
export const GET_ACTIVE_BOARD = 'GET_ACTIVE_BOARD';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const RENAME_CATEGORY = 'RENAME_CATEGORY';
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY';
export const GET_ACTIVE_CATEGORY = 'GET_ACTIVE_CATEGORY';

export const TASK_FORM_VISIBILITY = 'TASK_FORM_VISIBILITY';
export const IS_EDIT = 'IS_EDIT';
export const GET_TASK_TO_EDIT = 'GET_TASK_TO_EDIT';

export const GET_TASKS = 'GET_TASKS';
export const RESET_TASK = 'RESET_TASK';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SET_TASK_STATUS = 'SET_TASK_STATUS';
export const SET_SUBTASK_STATE = 'SET_SUBTASK_STATE';
export const SET_TASK_EXTEND_STATE = 'SET_TASK_EXTEND_STATE';

export const GET_SESSION = 'GET_SESSION';
export const CLEAR_SESSION = 'GET_SESSION';
export const RELOAD = 'RELOAD';
export const UPDATE_DONE = 'UPDATE_DONE';

export const GET_OR_CREATE_USER = 'GET_OR_CREATE_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const PASSWORD_RESET_REQUEST_SUCCESS = 'PASSWORD_RESET_REQUEST_SUCCESS';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';


export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';

export const GET_ERRORS = 'GET_ERRORS';
export const GET_MESSAGES = 'GET_MESSAGES';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CLEAR_MSG_ERR = 'CLEAR_MSG_ERR'

export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const INIT_TASKS = 'INIT_TASKS';